stages:
    - build
    - test

build:
    stage: build
    script:
        - echo "Building"
        - mkdir build1
        - touch build1/info.txt
    artifacts:
        paths:
            - build1/
test:
    stage: test
    script:
        - echo "testing1"
        - test -f "build1/info.txt"